### ISSUE TITLE
Random dense packing 

### ISSUE THREAD

**Issue by rpshi** [MosGeo/ParticlePack#4]
Hi Mustafa,

To achieve a random dense packing, both transnational and rotational shaking can be applied. 

Just wondering what is the criterion used to determine whether the dense packing is achieved or not?

When applying a shaking, the lid should should be on in order to prevent particle leaving the container?

Thanks for the great tool!

Cheers,

**Comment by MosGeo** [comment]
For one of the papers, the check was based on resultant porosity of monospherical random grain pack. That value is known. The shaking was applied while deposition was happening so the lid was open. The shaking is very small and the container size should be large enough so that particles don't leave the container.
